POST http://localhost:3001/api/users
Content-Type: application/json

{
  "username": "test@example.com",
  "name": "Test User"
}

###

PUT http://localhost:3001/api/users/test@example.com
Content-Type: application/json

{
  "name": "Test User 2"
}
